### PR TITLE
Removed some weird code to get the document associated with an URI

### PR DESCRIPTION
**Pull request by Delta-dev-99**
Removed some weird code to get the document associated with an URI.
Also renamed a couple variables to make easier to read the source.
Hope this helps.

### CODE REVIEW

**Comment by dseight** [comment]
Could you please describe what issue are you trying to solve with this change?

**Comment by dseight** [comment]
Thank you for your contribution! 

Could you, please, fix variables naming to use `lowerCamelCase` so they will follow the project's coding style?

**Comment by Delta-dev-99** [comment]
Sure, I will

**Comment by Delta-dev-99** [comment]
Variable names should be OK in a minute. Im finishing it. I'm happy to contribute!

**Comment by dseight** [comment]
Tried to compile and encountered some import errors. @Delta-dev-99 , have you tested it?

**Comment by Delta-dev-99** [comment]
Let me check that out

**Comment by Delta-dev-99** [comment]
Did the first version (the one without the lowerCamelCase naming) compile? I think I tested it, but it was a long time ago. Now I don't even have the same system.

**Comment by Delta-dev-99** [comment]
Actually I found the bug. I forgot to rename the function name in the import.

**Comment by dseight** [comment]
> Did the first version (the one without the lowerCamelCase naming) compile? 

I've just checked it out — nope, it doesn't compile. Neither does the current one, because of the following error:
```
src/provider.ts:43:35 - error TS2304: Cannot find name 'TextDocument'.

43 export function getAsmUri(source: TextDocument): Uri {
                                     ~~~~~~~~~~~~
```

It's wise to test the code before pushing it. :slightly_smiling_face: 

To prevent such things from happening in the future, I've set up a Github Actions. Now it should be a little bit more transparent whether PR is buildable or not.

**Comment by Delta-dev-99** [comment]
Hello! I don't have a compiler available. I'm actually correcting this code from my cell phone (I love coding). I really hope it works now. This is embarrassing... I need your approval to run the github actions workflow. It would be a game changer to be able to at least check the code compiles.

**Comment by dseight** [comment]
Just for future PRs: I would not recommend changing variable names that are unrelated to PR functionality. But other than that, PR looks good now.

**Pull request merged**
